number1 = input("숫자 1:")
number2 = input("숫자 2:")
print("--------------------")
a = int(number1)
b = int(number2)
print(number1,"과",number2,"의 합은", a + b)
print(number1,"과", number2,"의 곱은", a * b)
print(number1,"과",number2,"의 빼기는", a - b)
print(number1,"과",number2,"의 몫은", a / b)
print(number1,"과",number2,"의 나머지는", a % b)