d = input("영어점수 입력 :")
f = input("수학점수 입력 :")
g = input("국어점수 입력 :")
q = int(d)
w = int(f)
e = int(g)
sum = q+w+e
print("--------------------")
print("세 과목의 합 =",q+w+e)
print("세 과목의 평균=",sum/3)